CSP\Domain\Gamification\Entity\Crew:
  type: entity
  repositoryClass: CSP\Infrastructure\Gamification\Repository\CrewRepository
  table: crews
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    text:
      type: string
      nullable: true
      length: 130
      options:
        fixed: false
      unique: true
    logo:
      type: string
      nullable: true
      length: 130
      options:
        fixed: false
    crewSize:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 0
      column: crew_size
    latestEnrollmentAt:
      type: datetime
      nullable: true
      column: latest_enrollment_at
    latestQuitAt:
      type: datetime
      nullable: true
      column: latest_quit_at
    isActive:
      type: boolean
      nullable: false
      column: is_active
      options:
        default: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    timezone:
      type: string
  oneToMany:
    crewMembers:
      targetEntity: CSP\Domain\Gamification\Entity\CrewMember
      mappedBy: crew
  oneToOne:
    user:
      targetEntity: CSP\Domain\User\Entity\User
      joinColumn:
          name: user_id
          referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [updatedLifeCycleDates]
    preUpdate: [updatedLifeCycleDates]