CSP\Domain\Gamification\Entity\LeaderBoardPlayer:
  type: entity
  repositoryClass: CSP\Infrastructure\User\Repository\LeaderBoardPlayerRepository
  table: leaderboard_players
  id:
    user:
      associationKey: true
    medal:
      associationKey: true
  fields:
    currentPosition:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 0
      column: current_position
    latestPosition:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 0
      column: latest_position
    credits:
      type: decimal
      nullable: false
      precision: 7
      scale: 3
      options:
        default: 0
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    createdAt:
      type: datetime
      nullable: false
      column: created_at
  manyToOne:
    user:
      targetEntity: CSP\Domain\User\Entity\User
      inversedBy: leaderBoardPlayers
      joinColumn:
          name: user_id
          referencedColumnName: id
    leaderBoard:
      targetEntity: CSP\Domain\Gamification\Entity\LeaderBoard
      inversedBy: leaderBoardPlayers
      joinColumn:
        name: leaderboard_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [updatedLifeCycleDates]
    preUpdate: [updatedLifeCycleDates]