CSP\Domain\Gamification\Entity\Prize:
  type: entity
  repositoryClass: CSP\Infrastructure\Gamification\Repository\PrizeRepository
  table: prizes
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    text:
      type: string
      nullable: true
      length: 130
      options:
        fixed: false
      unique: true
    score:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 0
      column: score
    isActive:
      type: boolean
      nullable: false
      column: is_active
      options:
        default: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    timezone:
      type: string
  oneToMany:
    earnedPrizes:
      targetEntity: CSP\Domain\Gamification\Entity\EarnedPrize
      mappedBy: earnedPrize
  lifecycleCallbacks:
    prePersist: [updatedLifeCycleDates]
    preUpdate: [updatedLifeCycleDates]