CSP\Domain\Gamification\Entity\Rank:
  type: entity
  repositoryClass: CSP\Infrastructure\Gamification\Repository\RankRepository
  table: ranks
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    text:
      type: string
      nullable: true
      length: 130
      options:
        fixed: false
      unique: true
    scoreLimit:
      type: integer
      nullable: false
      options:
        unsigned: true
        default: 0
      column: score_limit
    isActive:
      type: boolean
      nullable: false
      column: is_active
      options:
        default: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    timezone:
      type: string
  oneToOne:
    nextRank:
      targetEntity: CSP\Domain\Gamification\Entity\Rank
      joinColumn:
        name: next_rank_id
        referencedColumnName: id
        nullable: true
  lifecycleCallbacks:
    prePersist: [updatedLifeCycleDates]
    preUpdate: [updatedLifeCycleDates]