CSP\Domain\Gamification\Entity\LeaderBoard:
  type: entity
  repositoryClass: CSP\Infrastructure\Gamification\Repository\LeaderBoardRepository
  table: leaderboards
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    text:
      type: string
      nullable: true
      length: 130
      options:
        fixed: false
      unique: true
    description:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
    isActive:
      type: boolean
      nullable: false
      column: is_active
      options:
        default: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    timezone:
      type: string
  oneToMany:
    leaderBoardPlayers:
      targetEntity: CSP\Domain\Gamification\Entity\LeaderBoardPlayer
      mappedBy: leaderBoard
  lifecycleCallbacks:
    prePersist: [updatedLifeCycleDates]
    preUpdate: [updatedLifeCycleDates]